### ISSUE TITLE
Crear componente Home

### ISSUE THREAD

**Issue by MacarenaRodriguez1993** [MacarenaRodriguez1993/Emme-3D#21]
- [x] #22  crear carousel con imagenes - flechas ( --> <-- ) para cambiar de imagen. 

- [ ] #23  crear componente mejores valorados para mostrar los productos mejores valorados 

- [ ] #24  crear componentes noticias : aquí va informacion de promociones o ultimas noticias referidas a impresion3d

**Comment by Pau-Marin** [comment]
Para la Week 1 creo que sería mejor una Home más sencilla y crear esos componentes de cara a la Week 2 🤔
